# getting users input
print('\ngetting users input***************\n')
name = input('input your name: ')
age = int(input('age: '))
print('your name '+name+" age is ",age)
sentence = input('enter sen: ')
print('your sen.. is :'+ sentence)
word1 = input('enter replace :')
word2 = input('enter replace it with :')
print(sentence.replace(word1,word2))